
### GET /v1/health
GET http://localhost:3000/v1/health

### ======================= USERS =======================
### GET /v1/users/userID
GET http://localhost:3000/v1/users/7

### Add follower
### PUT /v1/users/userID/follow 
PUT http://localhost:3000/v1/users/25/follow
Content-Type: application/json

{
  "current_user_id": 7
}

### Remove follower
### PUT /v1/users/userID/unfollow
PUT http://localhost:3000/v1/users/20/unfollow
Content-Type: application/json

{
  "current_user_id": 7
}

### ======================= POST =======================
### GET /v1/posts/postID
GET http://localhost:3000/v1/posts/144

### POST create post
POST http://localhost:3000/v1/posts/
Content-Type: application/json

{
  "title": "New post",
  "content": "Hey guys, this is my fourth post",
  "tags": ["go", "backend", "postgres"]
}

### DELETE /v1/posts/postID
DELETE http://localhost:3000/v1/posts/209

### PATCH update post
PATCH http://localhost:3000/v1/posts/6
Content-Type: application/json

{
  "title": "New post title",
  "content": "Hey guys!. This is my updated content!"
}

### ======================= COMMENTS =======================
### POST create comment
POST http://localhost:3000/v1/posts/144/comments
Content-Type: application/json

{
  "userID": 50,
  "content": "Hey guys, this is my important comment"
}

### ======================= Feed =======================
### GET /v1/users/feed 
### options that can be used:
### limit=n, offset=n, search=key, tags=key1,key2 ,since,until=
### NOTE - tags search inside one post
GET http://localhost:3000/v1/users/feed?search=home&tags=Yoga,Mental Health