
### GET /v1/health
GET http://localhost:3000/v1/health

### GET /v1/posts/postID
GET http://localhost:3000/v1/posts/6

### POST create post
POST http://localhost:3000/v1/posts/
Content-Type: application/json

{
  "title": "New post",
  "content": "Hey guys, this is my fourth post",
  "tags": ["go", "backend", "postgres"]
}

### DELETE /v1/posts/postID
DELETE http://localhost:3000/v1/posts/8

### PATCH update post
PATCH http://localhost:3000/v1/posts/6
Content-Type: application/json

{
  "title": "New post title",
  "content": "Hey guys!. This is my updated content"
}